# Generated by Django 3.2.7 on 2021-09-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210927_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_file',
        ),
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Kapak Fotoğrafı Ekle'),
        ),
    ]
